using UnityEngine;

public class GameManager : MonoBehaviour {
  public GameObject foodPrefab;
  public GameObject playerPrefab;
  public GameObject player;

  // Data
  private readonly string[] usernames = {
    "BulletVortex",
    "HeadshotHavoc",
    "SilentSn1per",
    "PhantomStr1ke",
    "_TriggerFury_",
    "GhostReaper",
    "xSharpShooteRx",
    "BlazingBarrel",
    "RapidReload",
    "KillStreaker",
    "DarkScope",
    "FirestormX",
    "StealthViper",
    "ApexPredator",
    "DeathDealer7",
    "BloodhoundZ",
    "IronSight",
    "VenomBullet",
    "RagingHavoc",
    "ZeroMercy",
    "PigStupid",
    "Switch",
    "death_love",
    "broke",
    "Neckolas",
    "vancranade",
    "zi",
    "KEWKOMA",
    "Dre",
    "puma_pants",
    "HippieMidget",
    "NorseMystery1990",
    "stupuo2000",
    "Dyth",
    "OvertChancellor",
    "Fishboy0123",
    "ExessApplicant",
    "btn323",
    "BigJohn",
    "Supercell",
    "the rice guy",
    "dizzle",
    "pepperjez",
    "koda",
    "JPabi0",
    "allthekingsmen",
    "Daniel",
    "Bandit",
    "BrentFry",
    "Jess",
    "Pip",
    "seith",
    "sSa",
    "bunyip",
    "Bellan",
    "Ninjamas",
    "john smith",
    "Swords of B'ajj",
    "A sweetheart",
    "Mitch",
    "ozzikid",
    "Deeju",
    "beerbaron25",
    "smallpness",
    "shyballz",
    "Scarlet",
    "Gamdmarghee",
    "Gaming grandma",
    "One",
    "Sean",
    "darkcasper",
    "Tyker",
    "Lukssfg",
    "Iconic_Raider",
    "Noodlemofe",
    "Philldo",
    "idkfa",
    "ameen",
    "seibee",
    "SieyZyth",
    "FLOPPA",
    "justwater",
    "Shgnome",
    "smMom",
    "Leieozin",
    "xXLETHALXx",
    "Putin King",
    "bread",
    "Aieixo Caboose",
    "Dishes",
    "TressBoy",
    "Finish",
    "EarCymbol",
    "library",
    "m9",
    "hello",
    "srs_omega",
    "Smelly Kitten",
    "Arjs",
    "Minispace",
    "TERO KAAL",
    "AK47",
    "Minni",
    "Kito",
    "Cheeze",
    "Geese",
    "Mega Knight",
  };

  // Start is called before the first frame update
  void Start() {
      
  }

  // Update is called once per frame
  void Update() {
      
  }
}
